version: '3.8'

services:
  droid2api:
    build: .
    container_name: droid2api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    env_file:
      - .env
    environment:
      # Authentication configuration priority: FACTORY_API_KEY > DROID_REFRESH_KEY > client Authorization
      # 认证配置优先级：FACTORY_API_KEY > DROID_REFRESH_KEY > 客户端 Authorization
      PORT: ${PORT:-3000}
      NODE_ENV: ${NODE_ENV:-production}
      SESSION_SECRET: ${SESSION_SECRET:-change-me-in-production}
      AUTH_TOKEN: ${AUTH_TOKEN:-}
      FACTORY_API_KEY: ${FACTORY_API_KEY:-}
      DROID_REFRESH_KEY: ${DROID_REFRESH_KEY:-}
      TOKEN_STORE_PATH: ${TOKEN_STORE_PATH:-/app/data/token-store.json}
    volumes:
      - token-store:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:${PORT:-3000}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  token-store:
